// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrkysgtwkxxuxzhvrkpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJya3lzZ3R3a3h4dXh6aHZya3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Njg3MDksImV4cCI6MjA2ODQ0NDcwOX0.Wx9sQLSGqZ49SEIPRC9QviTj_MNXLtpOnXeTbfUakbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});